### ISSUE TITLE
gboard不生效

### ISSUE THREAD

**Issue by shugo-chara** [RC1844/MIUI_IME_Unlock#10]
环境：
mix fold （Android 11 MIUI12 21.5.18）
模块1.10

LSPosed
API 版本
93
框架版本
v1.3.5 (5551)
管理器版本
v1.3.5 (5551)
系统版本
11 (API 30)
设备
Mix Fold
系统架构
armeabi-v8a

gboard尝试多次不生效。其余搜狗百度等自带输入法一切正常。上一次用记得是出版的时候gboard是生效的。

**Comment by RC1844** [comment]
用不了就回退
