### ISSUE TITLE
［咨询］软件作者有把此模块的功能做进 App 的可能性吗？

### ISSUE THREAD

**Issue by WhiredPlanck** [RC1844/MIUI_IME_Unlock#18]
当然，这里不是说把 Xposed 模块置入 App，这显然很难完成。

我目前正在为[同文输入法](https://github.com/osfans/trime)活跃贡献中，为 #2 的目的而来咨询：App 是否能仿照模块的方法进行改写，或者另辟蹊跷，主动利用现有条件开启 MIUI 的全面屏优化呢？

我编程能力目前不太够，对 Android 了解也不够深入，但特别想达成上述目的，所以特地想来问问有无此方面的指引。不胜感激

**Comment by RC1844** [comment]
https://github.com/RC1844/MIUI_IME_Unlock/blob/8f060749c6548b05609a44eb43e99c9fdf9ee6d0/app/src/main/java/com/xposed/miuiime/MainHook.kt#L35 请看这一行，你只需要加入 com.android.internal.policy.PhoneWindow.setNavigationBarColor,设置导航栏样式皆可。其他问题如何触发尚不清楚

**Comment by WhiredPlanck** [comment]
> https://github.com/RC1844/MIUI_IME_Unlock/blob/8f060749c6548b05609a44eb43e99c9fdf9ee6d0/app/src/main/java/com/xposed/miuiime/MainHook.kt#L35
> 请看这一行，你只需要加入 com.android.internal.policy.PhoneWindow.setNavigationBarColor,设置导航栏样式皆可。其他问题如何触发尚不清楚

感谢回答，我花点时间探索一下。麻烦了 ~
