### ISSUE TITLE
同文输入法求适配

### ISSUE THREAD

**Issue by guixin233** [RC1844/MIUI_IME_Unlock#2]
好用，小米定制版输入法可以自动变色很香。本人用的中文输入法（同文无障碍版），确实有全面屏优化了，但只有剪贴板能用，不过也是有显示不全的bug，还有第一次切换输入法的logo显示问题，至于小爱什么的按了也没反应。不过最馋的还是自动变色了，特别希望能适配同文皮肤。
![Screenshot_2021-03-23-09-12-28-325_com android browser](https://user-images.githubusercontent.com/49135589/112077887-5f24fe00-8b4b-11eb-8d56-7617e49f4657.jpg)

**Comment by RC1844** [comment]
我还是不清楚你的需求是什么，还有就是，我不会去针对性的去适配某一款输入法的，这样不现实

**Comment by RC1844** [comment]
抱歉我还原不了你说的logo问题，还有底部颜色是输入法决定的，不需要我适配。

**Comment by ketal178** [comment]
> 我还是不清楚你的需求是什么，还有就是，我不会去针对性的去适配某一款输入法的，这样不现实

个人喜好用百度输入法，我想做这事，你愿意merge吗

**Comment by RC1844** [comment]
> 个人喜好用百度输入法，我想做这事，你愿意merge吗

欢迎啊
