### ISSUE TITLE
bug反馈，进入横屏再退出会导致抬高区域颜色不一致

### ISSUE THREAD

**Issue by lns103** [RC1844/MIUI_IME_Unlock#22]
目前是MIUI13开发版公测安卓12，对gboard伪装Google机型实现沉浸。
触发条件：进入横屏应用然后退出
恢复方法：切换深色模式唤起输入法，然后切换回来，或者强制停止输入法
正常状态：
![Screenshot_2022-03-31-10-34-12-713_com miui home jpg](https://user-images.githubusercontent.com/49310852/160964662-57577230-8966-4d97-b739-0665df5daece.png)
异常状态：
![Screenshot_2022-03-31-10-29-20-288_com miui home jpg](https://user-images.githubusercontent.com/49310852/160964693-1b01f361-de3b-4560-9cf5-224177f9bc0e.png)

**Comment by RC1844** [comment]
可能是翻转的时候重载了常用语，而输入法没有重新设置导航栏颜色

**Comment by lns103** [comment]
不知道能不能用 getNavigationBarColor() 来获取颜色，而不是劫持 setNavigationBarColor()

**Comment by RC1844** [comment]
双管齐下吧，getNavigationBarColor 时机不好把握

**Comment by fangzny1** [comment]
emmm，要不试试把小米桌面墓碑了，我发现墓碑小米桌面后这个问题就没有了，不知道是不是玄学

**Comment by RedLeaf007** [comment]
问题解决了吗

**Comment by vistre** [comment]
> 问题解决了吗

没有，

**Comment by xiaochopin** [comment]
所以有办法修吗

**Comment by RedLeaf007** [comment]
> 所以有办法修吗

已经合并代码了，着急就自己编译一个

**Comment by lns103** [comment]
> 所以有办法修吗

我自己编译了一个，用起来没问题，不想自己编译可以用我编译的
[Unlock_MIUI_IME-1.13_release_sign.zip](https://github.com/RC1844/MIUI_IME_Unlock/files/11711535/Unlock_MIUI_IME-1.13_release_sign.zip)

**Comment by xiaochopin** [comment]
后面我发现代码合并后就编译过一个放在酷安上了，貌似可用
该bug修复后用起来会更舒服了

**Comment by vistre** [comment]
> 

现在就只剩一个bug了，进入设置以后，下面会变透明
