### ISSUE TITLE
求适配HyperOS

### ISSUE THREAD

**Issue by devnakx** [RC1844/MIUI_IME_Unlock#27]
[HPOS_1.0.6_K70P.zip](https://github.com/RC1844/MIUI_IME_Unlock/files/13660708/HPOS_1.0.6_K70P.zip)

**Comment by devnakx** [comment]
zip 已包含 #17 要求提供的两个文件

**Comment by devnakx** [comment]
@RC1844 @keta1 @GSWXXN PTAL

**Comment by keta1** [comment]
先等我系统推送了 HyperOS
说好的 13 pro 首批现在都没推

**Comment by GSWXXN** [comment]
我更新了 HyperOS，模块功能一切正常，你可以再发一下lsp 的日志

**Comment by devnakx** [comment]
[LSPosed_2023-12-16T21_46_14.119058.zip](https://github.com/RC1844/MIUI_IME_Unlock/files/13692742/LSPosed_2023-12-16T21_46_14.119058.zip)
@GSWXXN

**Comment by GSWXXN** [comment]
从日志中可以看到看到lsp加载了模块，但没发现有什么异常信息。如果你确认模块没有被正确加载可以尝试：

1. 提取作用域内应用，并覆盖安装
2. 卸载模块，重新安装模块并激活
3. 卸载重装 LSPosed 框架

以上三点不一定需要同时操作，你可以每完成一点就去检查模块的加载情况

**Comment by devnakx** [comment]
> 从日志中可以看到看到lsp加载了模块，但没发现有什么异常信息。如果你确认模块没有被正确加载可以尝试：
> 
> 1. 提取作用域内应用，并覆盖安装
> 2. 卸载模块，重新安装模块并激活
> 3. 卸载重装 LSPosed 框架
> 
> 以上三点不一定需要同时操作，你可以每完成一点就去检查模块的加载情况

握草，第一步完成后就解决了，非常感谢！！
