### ISSUE TITLE
Gboard底部有概率發生不同色

### ISSUE THREAD

**Issue by Josh-CYL** [RC1844/MIUI_IME_Unlock#5]
K30 5G Speed xiaomi.eu 12.1.6(問題如圖)
![Screenshot_2021-04-19-07-06-27-238_com chrome beta](https://user-images.githubusercontent.com/66094375/115237522-3d6d6580-a14f-11eb-8295-c2ac2ff9b4fd.jpg)
![Screenshot_2021-04-19-20-16-34-664_com chrome beta](https://user-images.githubusercontent.com/66094375/115235135-6b04df80-a14c-11eb-9b3b-cc7191ab5c0b.jpg)

**Comment by RC1844** [comment]
能用就行
